### ISSUE TITLE
No such file or directory activate

### ISSUE THREAD

**Issue by p1g3** [lightless233/geye#9]
运行命令：chmod +x ./tools/*.sh && ./tools/start_web.sh

运行错误截图：

![image](https://user-images.githubusercontent.com/49426158/73850563-e8557480-4866-11ea-93a9-bf1a04d13654.png)

**Comment by lightless233** [comment]
`start_web.sh`里写死了`virtualenv`的路径为 `/geye/venv/bin/activate` ，启动的时候可以根据自己的需要调整一下 `start_web.sh` 脚本。
